#!/usr/bin/env node

import * as p from '@clack/prompts'
import pc from 'picocolors'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const CRM_DIR = path.join(ROOT, 'apps', 'crm')
const CONFIG_PATH = path.join(CRM_DIR, 'fund.config.ts')
const ENV_PATH = path.join(CRM_DIR, '.env.local')

const MODULES = [
  { value: 'deals', label: 'Deal Pipeline', hint: 'Application intake, voting, deliberations' },
  { value: 'portfolio', label: 'Portfolio Tracking', hint: 'Investments, valuations, terms' },
  { value: 'tickets', label: 'Tickets & Tasks', hint: 'Internal task management' },
  { value: 'meetings', label: 'Meetings & Notes', hint: 'Scheduling and collaborative notes' },
  { value: 'notifications', label: 'Notifications', hint: 'In-app notification system' },
  { value: 'news', label: 'News Feed', hint: 'AI-curated industry news' },
  { value: 'liveblocks', label: 'Collaborative Editing', hint: 'Requires Liveblocks API key' },
  { value: 'rejectionEmails', label: 'AI Rejection Emails', hint: 'Requires Anthropic API key' },
  { value: 'sms', label: 'SMS Notifications', hint: 'Requires Twilio account' },
]

// Modules enabled by default
const DEFAULT_ENABLED = ['deals', 'portfolio', 'tickets', 'meetings', 'notifications', 'news']

async function main() {
  console.clear()

  p.intro(pc.bgCyan(pc.black(' VCRM Setup ')))

  // Fund branding
  const branding = await p.group(
    {
      name: () =>
        p.text({
          message: 'What is your fund\'s name?',
          placeholder: 'Acme Ventures',
          validate: (v) => (v.length === 0 ? 'Fund name is required' : undefined),
        }),
      shortName: () =>
        p.text({
          message: 'Short name or abbreviation?',
          placeholder: 'AV',
          validate: (v) => (v.length === 0 ? 'Short name is required' : undefined),
        }),
      tagline: () =>
        p.text({
          message: 'One-line tagline for your fund?',
          placeholder: 'Investing in the future of AI',
        }),
      supportEmail: () =>
        p.text({
          message: 'Support email address?',
          placeholder: 'team@acmeventures.com',
        }),
      website: () =>
        p.text({
          message: 'Fund website URL?',
          placeholder: 'https://acmeventures.com',
        }),
    },
    {
      onCancel: () => {
        p.cancel('Setup cancelled.')
        process.exit(0)
      },
    }
  )

  // Module selection
  const selectedModules = await p.multiselect({
    message: 'Which modules do you want to enable? (space to toggle, enter to confirm)',
    options: MODULES.map((m) => ({
      value: m.value,
      label: m.label,
      hint: m.hint,
    })),
    initialValues: DEFAULT_ENABLED,
    required: false,
  })

  if (p.isCancel(selectedModules)) {
    p.cancel('Setup cancelled.')
    process.exit(0)
  }

  const enabledSet = new Set(selectedModules)

  // Generate fund.config.ts
  const s = p.spinner()
  s.start('Writing configuration')

  const logoText = branding.shortName.toUpperCase()
  const moduleEntries = MODULES.map((m) => {
    const enabled = enabledSet.has(m.value)
    return `    /** ${m.hint} */\n    ${m.value}: ${enabled},`
  }).join('\n\n')

  const configContent = `/**
 * Fund Configuration
 *
 * This is the single source of truth for your fund's branding and feature setup.
 * Generated by \`pnpm init-fund\` — you can edit this file directly at any time.
 */

export const fundConfig = {
  /** Your fund's full name (shown in metadata, emails, etc.) */
  name: '${escapeQuotes(branding.name)}',

  /** Short name or abbreviation */
  shortName: '${escapeQuotes(branding.shortName)}',

  /** One-line description of your fund */
  tagline: '${escapeQuotes(branding.tagline || '')}',

  /** Support email shown in error messages */
  supportEmail: '${escapeQuotes(branding.supportEmail || '')}',

  /** Your fund's website */
  website: '${escapeQuotes(branding.website || '')}',

  /** Branding configuration */
  branding: {
    /**
     * Logo text parts displayed in the navigation bar.
     * Each part can have a different font weight.
     */
    logo: [
      { text: '${escapeQuotes(logoText)}', weight: 'bold' as const },
    ],

    /** Primary brand color (used for accents, buttons, etc.) */
    primaryColor: '#1a1a1a',

    /** Font family (loaded from Google Fonts in layout.tsx) */
    font: 'Montserrat',

    /** Google Fonts URL - update if you change the font */
    fontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap',
  },

  /**
   * Feature modules - enable/disable sections of the CRM.
   * Disabled modules hide nav links and return 404 on their routes.
   */
  modules: {
${moduleEntries}
  },

  /**
   * Webhook field mapping for your application intake form.
   * Maps your form provider's field names to the CRM's expected fields.
   * Update these keys to match your form's field names/IDs.
   */
  webhookFieldMap: {
    companyName: 'q29_companyName',
    website: 'q31_websiteif',
    companyDescription: 'q30_companyDescription',
    founderNames: 'q26_typeA',
    founderLinkedins: 'q28_founderLinkedins',
    founderBios: 'q40_founderBios',
    primaryEmail: 'q32_primaryEmail',
    previousFunding: 'q35_haveYou',
    deckLink: 'q41_linkTo',
  },
} as const

export type FundConfig = typeof fundConfig
export type ModuleKey = keyof typeof fundConfig.modules
`

  fs.writeFileSync(CONFIG_PATH, configContent)

  // Generate .env.local with placeholders (don't prompt for API keys — they're too long to paste in terminal)
  if (!fs.existsSync(ENV_PATH)) {
    let envContent = `# VCRM Environment Variables
# Fill in your values below. Get Supabase keys from: Dashboard → Settings → API

# ---- Required: Supabase ----
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
`

    if (enabledSet.has('liveblocks')) {
      envContent += `
# ---- Liveblocks (Collaborative Editing) ----
# Get your key at https://liveblocks.io
NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY=
`
    }
    if (enabledSet.has('rejectionEmails')) {
      envContent += `
# ---- Anthropic (AI Rejection Emails) ----
ANTHROPIC_API_KEY=
`
    }
    if (enabledSet.has('sms')) {
      envContent += `
# ---- Twilio (SMS Notifications) ----
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=
`
    }

    fs.writeFileSync(ENV_PATH, envContent)
  }

  s.stop('Configuration written')

  // Summary
  const enabledModules = MODULES.filter((m) => enabledSet.has(m.value))
  const disabledModules = MODULES.filter((m) => !enabledSet.has(m.value))

  p.log.success(pc.green(`Fund: ${branding.name}`))

  if (enabledModules.length > 0) {
    p.log.info(
      pc.cyan('Enabled modules:\n') +
        enabledModules.map((m) => `  ${pc.green('✓')} ${m.label}`).join('\n')
    )
  }
  if (disabledModules.length > 0) {
    p.log.info(
      pc.dim('Disabled modules:\n') +
        disabledModules.map((m) => `  ${pc.dim('✗')} ${pc.dim(m.label)}`).join('\n')
    )
  }

  p.note(
    [
      `${pc.cyan('Next steps:')}`,
      '',
      `1. Add your Supabase keys to ${pc.cyan('apps/crm/.env.local')}`,
      `   ${pc.dim('(Supabase Dashboard → Settings → API)')}`,
      '',
      `2. Set up the database: ${pc.cyan('pnpm db:setup')}`,
      `   ${pc.dim('Connects to your database and runs all migrations')}`,
      '',
      `3. Create your first user: ${pc.cyan('pnpm create-user')}`,
      '',
      `4. Start the dev server: ${pc.cyan('pnpm dev')}`,
    ].join('\n'),
    'Almost there!'
  )

  p.outro(pc.green('Setup complete!'))
}

function escapeQuotes(str) {
  return str.replace(/'/g, "\\'")
}

main().catch((err) => {
  p.log.error(err.message)
  process.exit(1)
})
