/**
 * Fund Configuration
 *
 * This is the single source of truth for your fund's branding and feature setup.
 * Generated by `pnpm init-fund` — you can edit this file directly at any time.
 */

export const fundConfig = {
  /** Your fund's full name (shown in metadata, emails, etc.) */
  name: 'Nicks Fund',

  /** Short name or abbreviation */
  shortName: 'NF',

  /** One-line description of your fund */
  tagline: 'Building Stuff',

  /** Support email shown in error messages */
  supportEmail: '',

  /** Your fund's website */
  website: '',

  /** Branding configuration */
  branding: {
    /**
     * Logo text parts displayed in the navigation bar.
     * Each part can have a different font weight.
     */
    logo: [
      { text: 'NF', weight: 'bold' as const },
    ],

    /** Primary brand color (used for accents, buttons, etc.) */
    primaryColor: '#1a1a1a',

    /** Font family (loaded from Google Fonts in layout.tsx) */
    font: 'Montserrat',

    /** Google Fonts URL - update if you change the font */
    fontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap',
  },

  /**
   * Feature modules - enable/disable sections of the CRM.
   * Disabled modules hide nav links and return 404 on their routes.
   */
  modules: {
    /** Application intake, voting, deliberations */
    deals: true,

    /** Investments, valuations, terms */
    portfolio: true,

    /** Internal task management */
    tickets: true,

    /** Scheduling and collaborative notes */
    meetings: true,

    /** In-app notification system */
    notifications: true,

    /** AI-curated industry news */
    news: true,

    /** Requires Liveblocks API key */
    liveblocks: false,

    /** Requires Anthropic API key */
    rejectionEmails: false,

    /** Requires Twilio account */
    sms: false,
  },

  /**
   * Webhook field mapping for your application intake form.
   * Maps your form provider's field names to the CRM's expected fields.
   * Update these keys to match your form's field names/IDs.
   */
  webhookFieldMap: {
    companyName: 'YOUR_COMPANY_NAME_FIELD',
    website: 'YOUR_WEBSITE_FIELD',
    companyDescription: 'YOUR_DESCRIPTION_FIELD',
    founderNames: 'YOUR_FOUNDER_NAMES_FIELD',
    founderLinkedins: 'YOUR_FOUNDER_LINKEDINS_FIELD',
    founderBios: 'YOUR_FOUNDER_BIOS_FIELD',
    primaryEmail: 'YOUR_EMAIL_FIELD',
    previousFunding: 'YOUR_PREVIOUS_FUNDING_FIELD',
    deckLink: 'YOUR_DECK_LINK_FIELD',
  },
} as const

export type FundConfig = typeof fundConfig
export type ModuleKey = keyof typeof fundConfig.modules
